CREATE TABLE PROJET(
	ID INT AUTO_INCREMENT,
	INTITULE TEXT,
	PERIMETRE TEXT,
	PRIMARY KEY(ID)
);

CREATE TABLE SOUSPROJET(
	ID INT AUTO_INCREMENT,
	PID INT REFERENCES PROJET(ID) ON DELETE CASCADE,
	INTITULE TEXT,
	PERIMETRE TEXT,
	PRIMARY KEY(ID)
);